# Pipeline switches
use_wandb: true
wandb_project: nano-genie-pipeline
dataset: PICODOOM

# smaller shared model params
patch_size: 4
context_length: 4
frame_size: 64
latent_dim: 4 # for video tokenizer
num_bins: 2 # for video tokenizer
n_actions: 8
embed_dim: 128
num_heads: 8
hidden_dim: 256
num_blocks: 4

# simplest train settings
compile: false
tf32: true
amp: true
log_interval: 1
n_updates: 2
learning_rate: 0.0001
batch_size: 8

# Stage configs
video_tokenizer_config: configs/video_tokenizer.yaml
latent_actions_config: configs/latent_actions.yaml
dynamics_config: configs/dynamics.yaml

# Which stages to run
run_video_tokenizer: true
run_latent_actions: true
run_dynamics: true 
