# Training
batch_size: 500
n_updates: 300000
learning_rate: 0.01
log_interval: 2000

use_actions: true

# these can vary but for convenience, here
embed_dim: 32
num_heads: 8
hidden_dim: 128
num_blocks: 8

# Paths
video_tokenizer_path:
latent_actions_path:

# resume from checkpoint
checkpoint: