# Training
batch_size: 256
n_updates: 1
learning_rate: 0.0001
log_interval: 2500

# Model (must match tokenizer)
embed_dim: 128
num_heads: 8
hidden_dim: 256
num_blocks: 4

use_actions: true

# Paths
video_tokenizer_path: null
latent_actions_path: null

# Performance
amp: true
tf32: true
compile: false

# W&B
use_wandb: true
wandb_project: nano-genie
wandb_run_name: null

# Save
save: true
filename: null 