# paths (need if not get latest)
video_tokenizer_path: 
latent_actions_path: 
dynamics_path: 
use_latest_checkpoints: true

# inference params
dataset: PONG
preload_ratio:
device: mps # make sure to use correct device
generation_steps: 10
context_window: 2
fps: 2
temperature: 0.5 # 0 is argmax
teacher_forced: false # for testing/dev
prediction_horizon: 1 # how many masked frames to append and decode at a time

# action selection modes (lower takes priority)
use_actions: false # use random actions
use_gt_actions: false # use lam-inferred actions
use_interactive_mode: true # use user-inputted actions

# inference acceleration
amp: false
tf32: false
compile: false