video_tokenizer_path:
latent_actions_path:
dynamics_path:
device: cuda
generation_steps: 4
context_window: 3
fps: 2
temperature: 0.0
use_actions: false
teacher_forced: false
use_latest_checkpoints: true
prediction_horizon: 1
dataset: PICODOOM
use_gt_actions: true
