video_tokenizer_path: /workspace/nano-genie/results/2025_09_15_07_13_54/video_tokenizer/checkpoints/video_tokenizer_step_0_2025_09_15_07_15_32.pth
latent_actions_path: /workspace/nano-genie/results/2025_09_15_07_13_54/latent_actions/checkpoints/latent_actions_step_0_2025_09_15_07_17_27.pth
dynamics_path: /workspace/nano-genie/results/2025_09_15_07_58_44/dynamics/checkpoints/dynamics_step_0_2025_09_15_08_00_10.pth
device: cuda
generation_steps: 4
context_window: 3
fps: 2
temperature: 0.0
use_actions: true
teacher_forced: false
use_latest_checkpoints: false
prediction_horizon: 1
dataset: PICODOOM
use_gt_actions: false
