# Training
batch_size: 256
n_updates: 2000
learning_rate: 0.001
log_interval: 100
dataset: ZELDA
context_length: 4
frame_size: 128

# Model
n_actions: 16
patch_size: 8
embed_dim: 128
num_heads: 8
hidden_dim: 256
num_blocks: 4

# Performance
amp: true
tf32: true
compile: true

# W&B
use_wandb: true
wandb_project: nano-genie
wandb_run_name: null
wandb_media: false

# Save
save: true
filename: null 