# Training
batch_size: 256
n_updates: 1
learning_rate: 0.001
log_interval: 100

# Model
embed_dim: 128
num_heads: 8
hidden_dim: 256
num_blocks: 4

# Performance
amp: true
tf32: true
compile: false

# W&B
use_wandb: true
wandb_project: nano-genie
wandb_run_name: null
wandb_media: false

# Save
save: true
filename: null 