# Pipeline switches
use_wandb: true
wandb_project: nano-genie-pipeline
dataset: ZELDA

# Stage configs
vqvae_config: configs/vqvae.yaml
lam_config: configs/lam.yaml
dynamics_config: configs/dynamics.yaml

# Which stages to run
run_vqvae: true
run_lam: true
run_dynamics: true 