# Pipeline switches
use_wandb: true
wandb_project: nano-genie-pipeline
dataset: PICODOOM

# Stage configs
video_tokenizer_config: configs/video_tokenizer.yaml
lam_config: configs/lam.yaml
dynamics_config: configs/dynamics.yaml

# Which stages to run
run_video_tokenizer: true
run_lam: true
run_dynamics: true 