# wandb
use_wandb: true
wandb_project: nano-genie-pipeline

# dataset
dataset: POLE_POSITION
preload_ratio: 1.0

# shared model params
patch_size: 4
context_length: 4
frame_size: 64
latent_dim: 5 # for video tokenizer
num_bins: 4 # for video tokenizer
n_actions: 8

# performance
amp: true
tf32: true
compile: true

# distributed launch (torchrun)
distributed: true
nproc_per_node: 6
standalone: true

# stage configs
video_tokenizer_config: configs/video_tokenizer.yaml
latent_actions_config: configs/latent_actions.yaml
dynamics_config: configs/dynamics.yaml

# which stages to run
run_video_tokenizer: true
run_latent_actions: false
run_dynamics: true
