# Training
batch_size: 256
n_updates: 100000
learning_rate: 0.0004
log_interval: 2500


# Model
embed_dim: 128
num_heads: 8
hidden_dim: 256
num_blocks: 4

# Save/IO
save: true
filename: null
checkpoint: null
start_iteration: 0